### PR TITLE
update for 2019

### PR DESCRIPTION
**Pull request by kortschak**
Please take a look.

This is obviously contingent on availability, and also exactly where we decide to put Lloyds lecture.

### CODE REVIEW

**Comment by kortschak** [comment]
Nathan has suggested that he might get involved in the pracs, so that would help there.

**Comment by nathanhaigh** [comment]
What dates is Steve away is it just in Sept? I'm trying to schedule in a few things in Aug so need to know.

**Comment by jimmybgammyknee** [comment]
I think its all of September. Specific dates we'll need to wait for him

**Comment by steveped** [comment]
I'm formally on leave from Monday 16th September until Friday 11th October. I note there is a practical on Mon 16th Sept that I am down for, and I don't fly out until 10pm that night. I can possibly do it if needed.

**Pull request merged**
